notifications:
  commits:      commits@logging.apache.org
  issues:       notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label comment 

staging:
  profile: log4j2
  whoami: asf-staging
  subdir: content/log4j

publish:
  profile: ~
  whoami: asf-site
  subdir: content/log4j
