pages = [{"l":"api/index.html","n":"log4j-api-scala","t":"log4j-api-scala","d":"","k":"static"},
{"l":"api/org/apache/logging/log4j/scala.html","n":"org.apache.logging.log4j.scala","t":"package org.apache.logging.log4j.scala","d":"org/apache/logging/log4j/scala","k":"package"},
{"l":"api/org/apache/logging/log4j/scala/Logger$.html","n":"Logger","t":"object Logger","d":"org/apache/logging/log4j/scala/Logger$","k":"object"},
{"l":"api/org/apache/logging/log4j/scala/Logger$.html","n":"FQCN","t":"val FQCN: String","d":"org/apache/logging/log4j/scala/Logger$","k":"val"},
{"l":"api/org/apache/logging/log4j/scala/Logger$.html","n":"apply","t":"def apply(clazz: Class[_]): Logger","d":"org/apache/logging/log4j/scala/Logger$","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger$.html","n":"apply","t":"def apply(delegate: ExtendedLogger): Logger","d":"org/apache/logging/log4j/scala/Logger$","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"Logger","t":"class Logger extends AnyVal","d":"org/apache/logging/log4j/scala/Logger","k":"class"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline marker: Marker, inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline marker: Marker, inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline marker: Marker, inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline marker: Marker, inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline marker: Marker, inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline marker: Marker, inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"apply","t":"def apply(inline level: Level, inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"catching","t":"def catching(inline t: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"catching","t":"def catching(inline level: Level, inline t: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline marker: Marker, inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline marker: Marker, inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline marker: Marker, inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline marker: Marker, inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline marker: Marker, inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline marker: Marker, inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"debug","t":"def debug(inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"delegate","t":"val delegate: ExtendedLogger","d":"org/apache/logging/log4j/scala/Logger","k":"val"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline marker: Marker, inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline marker: Marker, inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline marker: Marker, inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline marker: Marker, inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline marker: Marker, inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline marker: Marker, inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"error","t":"def error(inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline marker: Marker, inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline marker: Marker, inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline marker: Marker, inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline marker: Marker, inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline marker: Marker, inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline marker: Marker, inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"fatal","t":"def fatal(inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline marker: Marker, inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline marker: Marker, inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline marker: Marker, inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline marker: Marker, inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline marker: Marker, inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline marker: Marker, inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"info","t":"def info(inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"logMessage","t":"def logMessage(level: Level, marker: Marker, message: Message, cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"logMessage","t":"def logMessage(level: Level, marker: Marker, message: CharSequence, cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"logMessage","t":"def logMessage(level: Level, marker: Marker, message: AnyRef, cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"throwing","t":"def throwing[T <: Throwable](inline t: T): T","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"throwing","t":"def throwing[T <: Throwable](inline level: Level, inline t: T): T","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline marker: Marker, inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline marker: Marker, inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline marker: Marker, inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline marker: Marker, inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline marker: Marker, inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline marker: Marker, inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"trace","t":"def trace(inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"traceEntry","t":"def traceEntry(): EntryMessage","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"traceEntry","t":"def traceEntry(inline params: AnyRef*): EntryMessage","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"traceEntry","t":"def traceEntry(inline message: Message): EntryMessage","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"traceExit","t":"def traceExit(): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"traceExit","t":"def traceExit[R](inline result: R): R","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"traceExit","t":"def traceExit(inline entryMessage: EntryMessage): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"traceExit","t":"def traceExit[R](inline entryMessage: EntryMessage, result: R): R","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"traceExit","t":"def traceExit[R](inline message: Message, result: R): R","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline marker: Marker, inline message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline marker: Marker, inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline marker: Marker, inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline marker: Marker, inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline marker: Marker, inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline marker: Marker, inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(message: Message): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline message: CharSequence): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline message: AnyRef): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline message: Message, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline message: CharSequence, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logger.html","n":"warn","t":"def warn(inline message: AnyRef, inline cause: Throwable): Unit","d":"org/apache/logging/log4j/scala/Logger","k":"def"},
{"l":"api/org/apache/logging/log4j/scala/Logging.html","n":"Logging","t":"trait Logging","d":"org/apache/logging/log4j/scala/Logging","k":"trait"},
{"l":"api/org/apache/logging/log4j/scala/Logging.html","n":"logger","t":"val logger: Logger","d":"org/apache/logging/log4j/scala/Logging","k":"val"},
{"l":"api/org/apache/logging/log4j/scala/LoggingContext$.html","n":"LoggingContext","t":"object LoggingContext extends Map[String, String]","d":"org/apache/logging/log4j/scala/LoggingContext$","k":"object"},
{"l":"docs/index.html","n":"log4j-api-scala","t":"log4j-api-scala","d":"","k":"static"}];